name: Testes qualitativos

on:
  push:
    branches: [ "actions" ]

jobs:
  padrao-de-codigo:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: '8.1'
        psr: 'PSR12'

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - uses: actions/checkout@v3

    - name: Definir arquivo de ambiente
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Instalar Dependências
      run: composer require squizlabs/php_codesniffer --working-dir tests -q --no-interaction --no-progress

    - name: Verificar padrão de código
      run: |
        ./tests/vendor/bin/phpcs --standard=${{ matrix.psr }} ./app
        ./tests/vendor/bin/phpcs --standard=${{ matrix.psr }} ./routes

  testes:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_CONNECTION: pgsql
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE: postgres
      APP_URL: localhost:8080
      DB_PORT: 5432

    strategy:
    fail-fast: false
    matrix:
      postgres-version: '14'
      php-version: '8.1'
    
    services:
      postgres:
        image: ${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, fileinfo, pgsql
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Definir arquivo de ambiente
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Instalar Dependências
      run: |
        composer install -q --no-interaction --no-progress
        php artisan key:generate

    - name: Limpar cache/config
      run: php artisan config:clear

    - name: Executar migrations
      run: php artisan migrate -v --seed

    - name: Realizar testes
      run: php artisan test
