name: Verificar funcionalidades

on:
  push:
    branches: [ "actions" ]

jobs:
  padrao-de-codigo:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3

    - name: Definir arquivo de ambiente
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Instalar Dependências
      run: composer require --working-dir tests -q --no-interaction --no-progress

    - name: Verificar padrão de código
      run: |
        ./tests/vendor/bin/phpcs --standard=PSR12 ./app
        ./tests/vendor/bin/phpcs --standard=PSR12 ./routes

  testes:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kaitos
        ports:
          - 5432:5432

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - uses: actions/checkout@v3

    - name: Definir arquivo de ambiente
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Instalar Dependências
      run: composer install -q --no-interaction --no-progress

    - name: Criar banco
      env:
        DATABASE_USER: postgres
        DATABASE_PORT: 5432
        POSTGRES_HOST: postgres
        POSTGRES_DB: kaitos
      run: createdb kaitos

    - name: Executar migrations
      run: php artisan migrate -q --seed

    - name: Realizar testes
      run: php artisan test
